"""add Department

Revision ID: 313ae4851089
Revises: e9c876ac0c19
Create Date: 2025-04-02 15:54:34.686963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313ae4851089'
down_revision = 'e9c876ac0c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
