"""rename address

Revision ID: 73471867a9a1
Revises: 18d6917b0e2c
Create Date: 2025-04-02 16:09:57.054602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73471867a9a1'
down_revision = '18d6917b0e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
